# Generated by Django 3.2.7 on 2021-10-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=10)),
                ('dorm', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100)),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.student')),
            ],
        ),
    ]
