# Generated by Django 3.2.7 on 2021-09-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=4)),
                ('sname', models.CharField(max_length=255)),
                ('scontact', models.CharField(max_length=255)),
            ],
        ),
    ]
