# Generated by Django 3.2.7 on 2021-09-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sudent',
            new_name='Student',
        ),
    ]
